import React, { forwardRef } from "react";
import StatCard from "./StatCard";
import SubmissionPieChart from "./SubmissionPieChart";
import SchoolPerformanceChart from "./SchoolPerformanceChart";
import SubmissionLineChart from "./SubmissionLineChart";
import { getDashboardStats } from "../../../utils/dashboardStats";

const DirectorPdfReport = forwardRef(({
    submissions,
    pieChartData,
    schoolData,
    lineData,},
ref
) => {
  const stats = getDashboardStats(submissions)
return (

<div
    ref={ref}
    className="bg-white p-8 w-[900px]"
>

<h1 className="text-3xl font-bold text-center">
Federal University of Technology, Minna
</h1>

<h2 className="text-xl text-center mt-2">
Assignment of Responsibility System
</h2>

<h3 className="text-lg text-center mb-8">
Director Analytics Report
</h3>

<div className="grid grid-cols-5 gap-4 mb-8">
  {stats.map((item, index) => (
    <StatCard
      key={index}
      title={item.title}
      value={item.value}
      icon={item.icon}
      subtitle={item.subtitle}
      iconBg={item.iconBg}
    />
  ))}
</div>

<div className="mb-8">
  <SubmissionPieChart data={pieChartData} />
</div>

<div className="mb-8">
  <SchoolPerformanceChart schoolsData={schoolData} activeChart={null} setActiveChart={() => {}} />
</div>
<div className="mb-8">
  <SubmissionLineChart data={lineData} />
</div>

<div className="mt-10 border-t pt-4 text-sm text-gray-600">
  <p>
    This report was automatically generated by the Assignment of
    Responsibility Management System.
  </p>

  <p className="mt-2">
    Generated on: {new Date().toLocaleString()}
  </p>
</div>

</div>

);

}
);

export default DirectorPdfReport;